#!/bin/sh

# Do not start `xrdb` processes in the background to avoid race conditions.
xrdb "$XDG_CONFIG_HOME/x11/Xresources"

# My custom screen setup.
mirror-displays

feh --bg-scale ~/.local/share/cost-risk.jpg &
compton &
dunst &

# Otherwise my eyes are just bleeding...
redshift -P &

# Allow me to stream to my remarkable with: restream -p
# ssh-agent will (by default) fork and thus does not need to be run with &
eval $(ssh-agent)
[ -f ~/.ssh/remarkable ] && ssh-add ~/.ssh/remarkable
