#!/bin/sh


# Do not start `xrdb` processes in the background to avoid race conditions.
xrdb "$XDG_CONFIG_HOME/x11/Xresources"
# Map caps to escape (vim stuff)
setxkbmap -option caps:escape &

# Fixes slow startup times of gnome applications
dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY

# My custom screen setup.
prefer-external-display

feh --bg-scale ~/.local/share/wall.jpg &
compton &
dunst &

# These progs I install manually so they might not yet be present
[ -n "$(command -v dropbox)" ] && dropbox start &


# Otherwise my eyes are just bleeding...
redshift -P &

# Allow me to stream to my remarkable with: restream -p
# ssh-agent will (by default) fork and thus does not need to be run with &
eval $(ssh-agent)
# NOTE: Generate a new ssh-key just for the remarkable without password.
# Otherwise it doesn't seem to work.
[ -f ~/.ssh/remarkable ] && ssh-add ~/.ssh/remarkable
